
/**
 * https://projecteuler.net/problem=2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * Answer: 4613732
 * Submitted: 20/08/2014
 * Account: c.lorking
 * 
 */

import java.util.*;

public class eulerP2
{    
    public static void main (String[] args) {
        Set<Integer> nums = new HashSet<Integer>();
        int x = 1;
        int y = 2;
        int z = x+y;
        int total = 0;
        int limit = 4000000;

        while (z < limit) {
            if (x%2==0) {nums.add(x);}
            if (y%2==0) {nums.add(y);}
            if (z%2==0) {nums.add(z);}

            x = y;
            y = z;
            z = x+y;
        }

        for (int i : nums){
            total+=i;            
        }

        System.out.println("Total sum of even valued terms under "+limit+" = "+total);
    }
}
